name: to_de_list_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  uuid: ^4.5.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  injectable: ^2.4.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

